### ISSUE TITLE
ble.sh makes nix-shell die trying to enter the new shell

### ISSUE THREAD

**Issue by raccoonasdf** [raccoonasdf/raccoonpkgs#1]
should figure out whether this is a me issue or a ble.sh issue
i'll look into it later

**Comment by akinomyoga** [comment]
Just in case, maybe this is related to the issue recently reported at https://github.com/akinomyoga/ble.sh/issues/169. This is a compatibility issue, and several workarounds are now in the latest version of `ble.sh`.

**Comment by raccoonasdf** [comment]
> Just in case, maybe this is related to the issue recently reported at [akinomyoga/ble.sh#169](https://github.com/akinomyoga/ble.sh/issues/169). This is a compatibility issue, and several workarounds are now in the latest version of `ble.sh`.

the issue is indeed fixed, thank you for letting me know :)
